---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(ggh4x)
library(ggstance)
cbPalette <- c('#1b9e77', '#e7298a', '#d95f02', '#FFC000', '#8b8680')
# clf_string <- 'treatsvm_'
# out_string <- 'outsvm_'
# out_string_2 <- 'outcomesvm_'
clf_string <- ''
out_string <- ''
out_string_2 <- 'outcomelr_'
# clf_string <- 'treatgbm_'
# out_string <- 'outgbm_'
# out_string_2 <- 'outcomegbm_'
split_type <- 'cv'
num_iters <- '5'
split_type <- 'bootstrap'
num_iters <- '1000'
nu_string <- 'nuplugin_'
```


```{r}
for (feats in 2:10){
  for (i in 1:1){
    input_paths <- c(paste0('./results/amazon_synthetic/ovb/pr_label_synthetic_direct_iso_effects_', 
        clf_string, out_string,  sprintf('features%d_', feats), sprintf('type%d_', i), nu_string,
        split_type, num_iters, '_long.csv'),
      paste0('./results/hk/hk_nocorr_iso_effects_', clf_string, out_string, 
        sprintf('type%d_', i), split_type, num_iters, '_long.csv'),
      paste0('./results/hk/hk_commitbravecorr_iso_effects_', clf_string, out_string, 
        sprintf('type%d_', i), split_type, num_iters, '_long.csv'),
      paste0('./results/hk/hk_speeches_', out_string_2, 'iso_effects_', clf_string, out_string, 
        sprintf('type%d_', i), split_type, num_iters, '_long.csv'))

    output_images <- c(paste0('./plots/amazon_synthetic/ovb/pr_label_synthetic_direct1.00.0_iso_effects_', 
        clf_string, out_string, sprintf('features%d_', feats), sprintf('type%d_', i), nu_string, 
        split_type, num_iters, '.pdf'),
      paste0('./plots/hk/hk_nocorr_iso_effects_', clf_string, out_string, 
        sprintf('type%d_', i), split_type, num_iters, '.pdf'),
      paste0('./plots/hk/hk_commitbravecorr_iso_effects_', clf_string, out_string, 
        sprintf('type%d_', i), split_type, num_iters, '.pdf'),
      paste0('./plots/hk/hk_speeches_', out_string_2, 'iso_effects_', clf_string, out_string, 
        sprintf('type%d_', i), split_type, num_iters, '.pdf'))

    for (j in 1:4){
      input_path <- input_paths[j]
      output_image <- output_images[j]
      df <- read.csv(input_path)
      names(df)[names(df) == 'feature'] <- 'treatment'
      ggplot(df, aes(x=ate, y=treatment)) + 
        geom_point(aes(color=estimate_type), position=ggstance::position_dodgev(height=0.5)) +
        geom_errorbar(aes(xmin=lower, xmax=upper, color=estimate_type),
                      position=ggstance::position_dodgev(height=0.5),
                      width=0.25) +
        geom_vline(xintercept=0, linetype=3) +
        # ggtitle('Effects of language attributes on opinions of 2019 HK protests') + 
        theme_minimal() +
        scale_colour_manual(values=cbPalette, breaks=c('true', 'ipw', 'dr', 'outcome model', 'naive')) +
        # scale_colour_discrete(breaks=c('source', 'transported', 'target')) + 
        theme(legend.position='top', axis.title.y=element_blank(), plot.title = element_text(hjust = 0.5),
              axis.text=element_text(size=18), legend.title=element_blank(), legend.text=element_text(size=18), axis.title.x=element_text(size=20))  +
        coord_cartesian(xlim=c(-10, 10))
      
      ggsave(output_image, width=8, height=10, device='pdf')
    }
  }
}
```


```{r}
for (feats in 2:10){
  for (i in 1:3){
    input_paths <- c(paste0('./results/amazon_synthetic/ovb/pr_label_synthetic_direct_iso_effects_', 
        clf_string, out_string, sprintf('features%d_', feats), sprintf('type%d_', i), nu_string, 'norm_',
        split_type, num_iters, '_long.csv'),
      paste0('./results/hk/hk_nocorr_iso_effects_', clf_string, out_string, 
        sprintf('type%d_norm_', i), 
        split_type, num_iters, '_long.csv'),
      paste0('./results/hk/hk_commitbravecorr_iso_effects_', clf_string, out_string, 
        sprintf('type%d_norm_', i),
        split_type, num_iters, '_long.csv'),
      paste0('./results/hk/hk_speeches_', out_string_2, 'iso_effects_', clf_string, out_string, 
        sprintf('type%d_norm_', i),
        split_type, num_iters, '_long.csv'))

    output_images <- c(paste0('./plots/amazon_synthetic/ovb/pr_label_synthetic_direct1.00.0_iso_effects_', 
        clf_string, out_string, sprintf('type%d_norm_', i), split_type, num_iters, '.pdf'),
      paste0('./plots/hk/hk_nocorr_iso_effects_', clf_string, out_string, 
        sprintf('type%d_norm_', i),
        split_type, num_iters, '.pdf'),
      paste0('./plots/hk/hk_commitbravecorr_iso_effects_', clf_string, out_string, 
        sprintf('type%d_norm_', i),
        split_type, num_iters, '.pdf'),
      paste0('./plots/hk/hk_speeches_', out_string_2, 'iso_effects_', clf_string, out_string, 
        sprintf('type%d_norm_', i),
        split_type, num_iters, '.pdf'))
    for (j in 1:4){
      input_path <- input_paths[j]
      output_image <- output_images[j]
      df <- read.csv(input_path)
      names(df)[names(df) == 'feature'] <- 'treatment'
      ggplot(df, aes(x=ate, y=treatment)) + 
        geom_point(aes(color=estimate_type), position=ggstance::position_dodgev(height=0.5)) +
        geom_errorbar(aes(xmin=lower, xmax=upper, color=estimate_type),
                      position=ggstance::position_dodgev(height=0.5),
                      width=0.25) +
        geom_vline(xintercept=0, linetype=3) +
        # ggtitle('Effects of language attributes on opinions of 2019 HK protests') + 
        theme_minimal() +
        scale_colour_manual(values=cbPalette, breaks=c('true', 'ipw', 'dr', 'outcome model', 'naive')) +
        # scale_colour_discrete(breaks=c('source', 'transported', 'target')) + 
        theme(legend.position='top', axis.title.y=element_blank(), plot.title = element_text(hjust = 0.5),
              axis.text=element_text(size=18), legend.title=element_blank(), legend.text=element_text(size=18), axis.title.x=element_text(size=20))  +
        coord_cartesian(xlim=c(-10, 10))
      
      ggsave(output_image, width=8, height=10, device='pdf')
    }
  }
}
```

```{r}
clf_df <- read.csv('./results/amazon_synthetic/treatment_clf_accuracy.csv')
output_image <- './plots/amazon_synthetic/treatment_clf_accuracy.pdf'
ggplot(clf_df, aes(x = treatment, y = accuracy, fill = model)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Amazon treatment clf test accuracy",
       x = "Treatment",
       y = "Accuracy",
       fill = "Model") +
  theme_minimal() +
  coord_cartesian(ylim=c(0.5, 1))

ggsave(output_image, width=10, height=6, device='pdf')
```

```{r}
clf_df <- read.csv('./results/hk/treatment_clf_accuracy_corr.csv')
output_image <- './plots/hk/treatment_clf_accuracy_corr.pdf'
ggplot(clf_df, aes(x = treatment, y = accuracy, fill = model)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "HK (commitment/bravery corr) treatment clf test accuracy",
       x = "Treatment",
       y = "Accuracy",
       fill = "Model") +
  theme_minimal() +
  coord_cartesian(ylim=c(0.5, 1))

ggsave(output_image, width=10, height=6, device='pdf')
```

```{r}
clf_df <- read.csv('./results/hk/treatment_clf_accuracy_nocorr.csv')
output_image <- './plots/hk/treatment_clf_accuracy_nocorr.pdf'
ggplot(clf_df, aes(x = treatment, y = accuracy, fill = model)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "HK (no corr) treatment clf test accuracy",
       x = "Treatment",
       y = "Accuracy",
       fill = "Model") +
  theme_minimal() +
  coord_cartesian(ylim=c(0.5, 1))

ggsave(output_image, width=10, height=6, device='pdf')
```